version: '3'
services:
  memo-nginx:
    image: ${REGISTRY_HOST}/memo-nginx:${REGISTRY_PRODUCTION_TAG}
    restart: always
    depends_on:
      - memo-php-fpm
    ports:
      - "23001:80"
    env_file: .env
  memo-php-fpm:
    image: ${REGISTRY_HOST}/memo-php-fpm:${REGISTRY_PRODUCTION_TAG}
    restart: always
    env_file: .env
    depends_on:
      - memo-redis
  memo-postgres:
    image: ${REGISTRY_HOST}/memo-postgres:${REGISTRY_PRODUCTION_TAG}
    restart: always
    volumes:
      - memo-postgres:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "54321:5432"
  memo-php-cli:
    image: ${REGISTRY_HOST}/memo-php-cli:${REGISTRY_PRODUCTION_TAG}
    environment:
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: pgsql://memo:${POSTGRES_PASSWORD}memo-postgres:5432/memo
    depends_on:
      - memo-postgres
      - memo-redis
  memo-redis:
    image: redis:5.0-alpine
    command:
      - 'redis-server'
      - '--requirepass ${REDIS_PASSWORD}'
    restart: always
    volumes:
      - redis-data:/redis-data
    ports:
      - '${REDIS_OUTER_PORT}:6379'

volumes:
  memo-postgres:
  redis-data: