version: '3'
services:
  memo-nginx:
    build:
      context: .
      dockerfile: ./docker/production/nginx.dockerfile
    image: ${REGISTRY_HOST}/memo-nginx:${REGISTRY_PRODUCTION_TAG}
    env_file: .env
    depends_on:
      - memo-php-fpm
    ports:
      - '23001:80'
  memo-php-fpm:
    build:
      context: .
      dockerfile: ./docker/production/php-fpm.dockerfile
    image: ${REGISTRY_HOST}/memo-php-fpm:${REGISTRY_PRODUCTION_TAG}
    env_file: .env
  memo-postgres:
    image: ${REGISTRY_HOST}/memo-postgres:${REGISTRY_PRODUCTION_TAG}
    restart: always
    volumes:
      - memo-postgres:/var/lib/postgresql/data
    env_file: .env

volumes:
  memo-postgres:
