version: '3'
services:
  memo-nginx:
    build:
      context: ./docker/development
      dockerfile: nginx.dockerfile
    volumes:
      - ./:/app
    depends_on:
      - memo-php-fpm
    ports:
      - '42001:80'
  memo-php-fpm:
    build:
      context: ./docker/development
      dockerfile: php-fpm.dockerfile
    environment:
      APP_DEBUG: 1
    volumes:
      - ./:/app
  memo-php-cli-stage:
    build:
      context: ./docker/development
      dockerfile: php-cli.dockerfile
    environment:
      APP_DEBUG: 1
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
  memo-postgres-stage:
    image: postgres:11.2-alpine
    volumes:
      - memo-postgres-stage:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "54323:5432"
  memo-redis-stage:
    image: redis
    hostname: redis
    command: ["sh", "-c", "exec redis-server --requirepass ${REDIS_PASSWORD}"]
    restart: always
    volumes:
      - redis-data:/redis-data
    ports:
      - '${REDIS_OUTER_PORT}:6379'

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_OUTER_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "8081:8081"

volumes:
  memo-postgres-stage:
  composer:
  redis-data:
