# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    telegram_commands:
        /translate:
            text_response: 'What word do you want to translate?'
            action_class: Ig0rbm\Memo\TelegramAction\QuizAction
        /save:
            text_response: 'What word do you wont to save?'
            action_class: Ig0rbm\Memo\TelegramAction\SaveAction
        /quiz:
            text_response: 'Let`s quiz start'
            action_class: Ig0rbm\Memo\TelegramAction\QuizAction
        /quiz_answer:
            text_response: 'Question not found'
            action_class: Ig0rbm\Memo\TelegramAction\QuizAnswerAction
        /word_list_quiz:
            text_response: 'Let`s quiz start'
            action_class: Ig0rbm\Memo\TelegramAction\WordListQuizAction
        /show:
            text_response: 'Yor list is empty'
            action_class: Ig0rbm\Memo\TelegramAction\ShowAction
        /edit:
            text_response: 'Nothing to edit'
            action_class: Ig0rbm\Memo\TelegramAction\EditAction
        /switch:
            text_response: 'Choose translation direction'
            action_class: Ig0rbm\Memo\TelegramAction\ShowDirectionButtonAction
        /change:
            text_response: 'Yor direction now is %s'
            action_class: Ig0rbm\Memo\TelegramAction\ChangeDirectionAction
            aliases:
                - 'ru-en'
                - 'en-ru'
        /hello:
            text_response: 'Hello!'
            action_class: Ig0rbm\Memo\TelegramAction\HelloAction
        default:
            text_response: 'Undefined command'
            action_class: Ig0rbm\Memo\TelegramAction\TranslationAction

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Ig0rbm\Memo\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Ig0rbm\Memo\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Ig0rbm\Memo\Service\Telegram\TokenChecker:
        public: true
        arguments:
            $telegramSecretKey: '%env(TELEGRAM_SECRET)%'

    Ig0rbm\Memo\Service\Telegram\Command\CommandParser:
        arguments:
            $rawCommands: '%telegram_commands%'

    Ig0rbm\Memo\Service\Telegram\TelegramApiService:
        arguments:
            $client: '@eight_points_guzzle.client.telegram_api'
            $token: '%env(TELEGRAM_SECRET)%'

    Ig0rbm\Memo\Service\Translation\Yandex\YandexDictionaryApiService:
        arguments:
            $client: '@eight_points_guzzle.client.yandex_dictionary_api'
            $token: '%env(YANDEX_DICTIONARY_API_KEY)%'

    Ig0rbm\Memo\Service\Translation\Yandex\YandexTranslationApiService:
        arguments:
            $client: '@eight_points_guzzle.client.yandex_translation_api'
            $token: '%env(YANDEX_TRANSLATION_API_KEY)%'

    Ig0rbm\Memo\Service\Telegraph\ApiService:
        arguments:
            $client: '@eight_points_guzzle.client.telegraph_api'
            $token: '%env(TELEGRAPH_ACCESS_TOKEN)%'
        public: true

    Ig0rbm\Memo\EventListener\WordListEventListener:
        arguments:
            $manager: '@Ig0rbm\Memo\Service\WordList\Telegraph\WordListManager'
        tags:
            - { name: kernel.event_listener, event: 'memo.word_list_event', method: 'onWordListAction'}

    Ig0rbm\Memo\EventListener\Telegram\BeforeResponseSendEventListener:
        tags:
            - { name: kernel.event_listener, event: 'bot.before_send_response', method: 'onBeforeResponseSend'}

    Ig0rbm\Memo\EventListener\Message\CallbackQueryHandleListener:
        tags:
            - { name: kernel.event_listener, event: 'bot.message.callback_query_handle', method: 'onCallbackQueryHandle'}

    Ig0rbm\Memo\Service\Quiz\QuizStepBuilder: ~

    ##############################################################################################################
    #∨                                                                                                          ∨#
    #∨                                         telegram actions is here                                         ∨#
    #∨                                                                                                          ∨#
    ##############################################################################################################

    Ig0rbm\Memo\TelegramAction\TranslationAction:
        public: true

    Ig0rbm\Memo\TelegramAction\SaveAction:
        public: true

    Ig0rbm\Memo\TelegramAction\HelloAction:
        public: true

    Ig0rbm\Memo\TelegramAction\DefaultAction:
        public: true

    Ig0rbm\Memo\TelegramAction\ShowAction:
        public: true

    Ig0rbm\Memo\TelegramAction\EditAction:
        public: true

    Ig0rbm\Memo\TelegramAction\ShowDirectionButtonAction:
        public: true

    Ig0rbm\Memo\TelegramAction\QuizAction:
        public: true

    Ig0rbm\Memo\TelegramAction\WordListQuizAction:
        public: true

    Ig0rbm\Memo\TelegramAction\QuizAnswerAction:
        public: true

    Ig0rbm\Memo\TelegramAction\ChangeDirectionAction:
        public: true
