# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    telegram_commands:
        /start:
            text_response: ''
            action_class: Ig0rbm\Memo\TelegramAction\StartAction
        /help:
            text_response: ''
            action_class: Ig0rbm\Memo\TelegramAction\StartAction
        /translate:
            text_response: 'What word do you want to translate?'
            action_class: Ig0rbm\Memo\TelegramAction\QuizAction
        /save:
            text_response: 'What word do you wont to save?'
            action_class: Ig0rbm\Memo\TelegramAction\SaveAction
        /quiz:
            text_response: 'Let`s quiz start'
            action_class: Ig0rbm\Memo\TelegramAction\QuizAction
        /quiz_answer:
            text_response: 'Question not found'
            action_class: Ig0rbm\Memo\TelegramAction\QuizAnswerAction
        /quiz_settings:
            text_response: 'Choose one'
            action_class: Ig0rbm\Memo\TelegramAction\QuizSettingsAction
        /word_list_quiz:
            text_response: 'Let`s quiz start'
            action_class: Ig0rbm\Memo\TelegramAction\WordListQuizAction
        /quiz_reminder:
            text_response: 'Write remind time with format "hh:mm"'
            action_class: Ig0rbm\Memo\TelegramAction\QuizReminderAction
        /quiz_set_reminder:
            text_response: 'Your reminder is configure'
            action_class: Ig0rbm\Memo\TelegramAction\QuizSetReminderAction
            aliases:
                - '^(0[0-9]|1[0-9]|2[0-3]|[0-9]):[0-5][0-9]$'
        /edit_quiz_reminders:
            text_response: 'There are not reminders for editing'
            action_class: Ig0rbm\Memo\TelegramAction\EditQuizReminderAction
            aliases:
                - '^\⏰\s\s\s.+$'
                - '^\🤖\s\s\s.+$'
        /time_zone:
            text_response: 'Set your timezone'
            action_class: Ig0rbm\Memo\TelegramAction\TimezoneAction
            aliases:
                - '^\🕰\s\s\s.+$'
        /locale_edit:
            text_response: '🤖 push button to set your language'
            action_class: Ig0rbm\Memo\TelegramAction\AccountLocaleAction
            aliases:
                - '^\🔤\s\s\s.+$'
                - '🤖 push button to set your language'
        /location:
            action_class: Ig0rbm\Memo\TelegramAction\LocationAction
            text_response: 'Now we have your location'
        /location_cancel:
            action_class: Ig0rbm\Memo\TelegramAction\LocationCancelAction
            text_response: 'Your timezone was set as UTC'
            aliases:
                - '^\🚫\s\s\s.+$'
        /list:
            text_response: 'Yor list is empty'
            action_class: Ig0rbm\Memo\TelegramAction\ShowAction
            aliases:
                - '^\📋\s\s\s.+$'
        /edit:
            text_response: 'Nothing to edit'
            action_class: Ig0rbm\Memo\TelegramAction\EditAction
            aliases:
                - '^\📝\s\s\s.+$'
        /switch:
            text_response: 'Choose translation direction'
            action_class: Ig0rbm\Memo\TelegramAction\ShowDirectionButtonAction
        /change:
            text_response: 'Yor direction now is %s'
            action_class: Ig0rbm\Memo\TelegramAction\ChangeDirectionAction
            aliases:
                - '🇷🇺🇬🇧\s\s\sru-en'
                - '🇷🇺🇬🇧ru-en'
                - '🇬🇧🇷🇺\s\s\sen-ru'
                - '🇬🇧🇷🇺en-ru'
        /hello:
            text_response: 'Hello!'
            action_class: Ig0rbm\Memo\TelegramAction\HelloAction
        /settings:
            text_response: 'messages.settings_menu'
            action_class: Ig0rbm\Memo\TelegramAction\SettingsAction
            aliases:
                - '^\⚙\s\s\s.+$'
                - '^\↪️\s\s\s.+$'
        /close_settings:
            text_response: '🤖 menu was closed'
            action_class: Ig0rbm\Memo\TelegramAction\CloseSettingsAction
            aliases:
                - '^\❌\s\s\s.+$'
        /license_limit_handle:
            text_response: '🤖 limit reached'
            action_class: Ig0rbm\Memo\TelegramAction\LimitReachedHandler
        default:
            text_response: 'Undefined command'
            action_class: Ig0rbm\Memo\TelegramAction\TranslationAction

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Ig0rbm\Memo\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Ig0rbm\Memo\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Ig0rbm\Memo\Service\Telegram\TokenChecker:
        public: true
        arguments:
            $telegramSecretKey: '%env(TELEGRAM_SECRET)%'

    Ig0rbm\Memo\Service\Telegram\Command\CommandParser:
        arguments:
            $rawCommands: '%telegram_commands%'

    Ig0rbm\Memo\Service\Telegram\TelegramApiService:
        arguments:
            $client: '@eight_points_guzzle.client.telegram_api'
            $token: '%env(TELEGRAM_SECRET)%'

    Ig0rbm\Memo\Service\Translation\Yandex\YandexDictionaryApiService:
        arguments:
            $client: '@eight_points_guzzle.client.yandex_dictionary_api'
            $token: '%env(YANDEX_DICTIONARY_API_KEY)%'

    Ig0rbm\Memo\Service\Translation\Yandex\YandexTranslationApiService:
        arguments:
            $client: '@eight_points_guzzle.client.yandex_translation_api'
            $token: '%env(YANDEX_TRANSLATION_API_KEY)%'

    Ig0rbm\Memo\Service\TimeZone\ApiService:
        arguments:
            $client: '@eight_points_guzzle.client.timezonedb_api'
            $token: '%env(TIMEZONEDB_API_KEY)%'

    Ig0rbm\Memo\Service\TimeZone\AccountTimeZoneManager: ~

    Ig0rbm\Memo\EventListener\WordListEventListener:
        tags:
            - { name: kernel.event_listener, event: 'memo.word_list_event', method: 'onWordListAction'}

    Ig0rbm\Memo\EventListener\Telegram\BeforeResponseSendEventListener:
        tags:
            - { name: kernel.event_listener, event: 'bot.before_send_response', method: 'onBeforeResponseSend'}

    Ig0rbm\Memo\EventListener\Message\CallbackQueryHandleListener:
        tags:
            - { name: kernel.event_listener, event: 'bot.message.callback_query_handle', method: 'onCallbackQueryHandle'}

    Ig0rbm\Memo\Service\Telegram\TranslationService: ~

    ##############################################################################################################
    #∨                                                                                                          ∨#
    #∨                                         telegram actions is here                                         ∨#
    #∨                                                                                                          ∨#
    ##############################################################################################################

    Ig0rbm\Memo\TelegramAction\TranslationAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\SaveAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\HelloAction:
        public: true

    Ig0rbm\Memo\TelegramAction\DefaultAction:
        public: true

    Ig0rbm\Memo\TelegramAction\ShowAction:
        arguments:
            $botHost: '%env(BOT_HOST)%'
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]
    Ig0rbm\Memo\TelegramAction\EditAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\ShowDirectionButtonAction:
        public: true

    Ig0rbm\Memo\TelegramAction\QuizAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\WordListQuizAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\QuizAnswerAction:
        public: true

    Ig0rbm\Memo\TelegramAction\QuizSettingsAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\QuizReminderAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\ChangeDirectionAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\LocationAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\TimezoneAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\QuizSetReminderAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\LocationCancelAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\SettingsAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\CloseSettingsAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\EditQuizReminderAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\AccountLocaleAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\StartAction:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]

    Ig0rbm\Memo\TelegramAction\LimitReachedHandler:
        public: true
        calls:
            - [setTranslator, ['@Ig0rbm\Memo\Service\Telegram\TranslationService']]
